const INITDATA = 'INITDATA';
const INFOUPDATE = 'INFOUPDATE';
const SHOWLOADING = 'SHOWLOADING';
const HIDELOADING = 'HIDELOADING';
const FOLLOW = 'FOLLOW';
const AUTHENTICATION = 'AUTHENTICATION';
const NICKNAME = 'NICKNAME';
export { INITDATA, INFOUPDATE, SHOWLOADING, HIDELOADING, FOLLOW, AUTHENTICATION }